trigger:
- master
- v1.5.x-kernel-5.10

pool: Default

steps:
- task: CmdLine@2
  inputs:
    script: 'make release'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)/dist/artifacts'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
