trigger:
- v1.5.x-kernel-5.10

pool: Default

steps:
- script: 'make release'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.sourcedirectory)/dist/artifacts'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
