trigger:
- v1.5.x-kernel-5.10

pool: Default

steps:
- script: 'make release'

- script: |
    cd $(build.sourcesdirectory)
    git clone https://github.com/Confusingboat/ros-uefi
    cp $(build.sourcesdirectory)/dist/artifacts/rancheros.iso $(build.sourcesdirectory)/ros-uefi/rancheros.iso
    cd ros-uefi
    chmod +x make-uefi.sh
    ./make-uefi.sh

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/dist/artifacts'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/rancheros'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/ros-uefi/tmp/iso'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/rancheros-uefi'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/rancheros'
    ArtifactName: 'rancheros'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/rancheros-uefi'
    ArtifactName: 'rancheros-uefi'
    publishLocation: 'Container'
